name: autoledger
description: AutoLedger frontend app to manage small business finance.
version: 1.0.0+1
environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^1.4.0
  provider: ^6.0.5
  flutter_secure_storage: ^9.2.4
  speech_to_text: ^7.1.0
  flutter_tts: ^4.2.3
  file_picker: ^10.2.0
  image_picker: ^1.0.7
  path_provider: ^2.1.2
  path: ^1.8.3
  sqflite: ^2.3.0
  connectivity_plus: ^4.0.1
  pdf: ^3.10.1
  printing: ^5.11.0
  shared_preferences: ^2.2.2
  open_filex: ^4.3.2
  intl: ^0.20.2
  dio: ^5.4.1
  shimmer: ^3.0.0
  dart_openai: ^5.1.0
  google_mlkit_text_recognition: ^0.10.0
  aws_signature_v4: ^0.6.7
  flutter_local_notifications: ^17.1.0
  timezone: ^0.9.2
  fl_chart: ^0.66.3
  device_calendar: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.24.0

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/logo.png
    - lib/assets/illustrations/empty_contacts.png